create table folder (
id integer primary key generated by default as identity,
name text not null
);

create table note (
id integer primary key generated by default as identity,
name text not null,
modified timestamp default now() not null,
content text, 
folder_id integer references folder(id) on delete cascade not null
);
