CREATE TYPE item_options AS enum (
  'yes',
  'no',
  'maybe'
);

CREATE TYPE item_status AS enum (
  'buying',
  'selling',
  'unavailable',
  'fulfilled'
);

CREATE TABLE inventory (
  id integer PRIMARY KEY GENERATED BY
    DEFAULT AS IDENTITY,
    item_name text NOT NULL,
    item_body text,
    item_owner integer REFERENCES morkit_user (id) ON DELETE CASCADE NOT NULL,
    item_is item_status NOT NULL,
    item_list integer REFERENCES category_list (id) ON DELETE CASCADE NOT NULL,
);

CREATE TABLE msg (
  id integer PRIMARY KEY GENERATED BY
    DEFAULT AS IDENTITY,
    sender_id integer REFERENCES morkit_user (id) ON DELETE CASCADE NOT NULL,
    receiver_id integer REFERENCES morkit_user (id) ON DELETE CASCADE NOT NULL,
    send_time timestamp DEFAULT now() NOT NULL,
    content text,
    buy boolean DEFAULT FALSE NOT NULL,
    check_available boolean DEFAULT FALSE NOT NULL,
    rsp_buy item_options,
    rsp_check_available item_options,
    rsp_content text
);

CREATE TABLE category_list (
  id integer PRIMARY KEY GENERATED BY
    DEFAULT AS IDENTITY,
    list_owner integer REFERENCES morkit_user (id) ON DELETE CASCADE NOT NULL,
    list_name text NOT NULL
);

CREATE TABLE morkit_user (
  id integer PRIMARY KEY GENERATED BY
    DEFAULT AS IDENTITY,
    username text NOT NULL,
    since timestamp DEFAULT now() NOT NULL,
    password text NOT NULL,
    fullname text NOT NULL,
    desc text
);

