-- create an enum that has buy, check availability, both
-- drop columns for rsp_buy, rsp_both, rsp_check
-- create new column for rsp_type set to reference new enum
-- and another generic one for the response for that called rsp
